version: "3.9"

networks:
  default:
    external:
      # The network should be the same as TRAEFIK network
      name: traefik-global-proxy

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
  geodatadir:
    name: ${COMPOSE_PROJECT_NAME}_geodatadir
  pgdumps:
    name: ${COMPOSE_PROJECT_NAME}_pgdumps

services:
  client:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:client-${PROJECT_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./app/client
    volumes:
      - /app/node_modules
      - ./app/client:/app
    container_name: ${COMPOSE_PROJECT_NAME}_client
    hostname: ${COMPOSE_PROJECT_NAME}_client
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_client.loadbalancer.server.port=80"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_client.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_client.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_client.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_client.tls=true"

  geoserver:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:geoserver-${PROJECT_VERSION}
    build: ./app/geoserver
    container_name: ${COMPOSE_PROJECT_NAME}_geoserver
    hostname: ${COMPOSE_PROJECT_NAME}_geoserver
    volumes:
      - geodatadir:/opt/geoserver/data_dir
    environment:
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - COMMUNITY_EXTENSIONS=backup-restore-plugin
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_geoserver.loadBalancer.server.port=8080"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_geoserver.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/geoserver`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_geoserver.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_geoserver.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_geoserver.tls=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_redirect_web_secure.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_geoserver.middlewares=${COMPOSE_PROJECT_NAME}_redirect_web_secure"
    depends_on:
      - db
    restart: on-failure

  db:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:db-${PROJECT_VERSION}
    build: ./app/database
    container_name: ${COMPOSE_PROJECT_NAME}_db
    hostname: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # uncomment to enable remote connections to postgres
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  api:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:api-${PROJECT_VERSION}
    build:
      context: ./app/api
    container_name: ${COMPOSE_PROJECT_NAME}_api
    hostname: ${COMPOSE_PROJECT_NAME}_api
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB_NAME=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_CLOUDFRONT_URL=${AWS_CLOUDFRONT_URL}
      - NODE_ENV=${API_ENVIRONMENT}
      - JWT_SECRET=${API_JWT_SECRET}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
      - API_PORT=3000
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_URL=https://${DOMAIN_NAME}/geoserver
    volumes:
      - geodatadir:/opt/geoserver/data_dir
      - /app/node_modules
      - ./app/api:/app
    user: "1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_api.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_api.loadBalancer.server.port=3000"
    depends_on:
      - db
      - geoserver
    restart: on-failure

  pgdumper:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:pgdumper-${PROJECT_VERSION}
    build: ./app/pgdumper
    container_name: ${COMPOSE_PROJECT_NAME}_pgdumper
    hostname: ${COMPOSE_PROJECT_NAME}_pgdumper
    volumes:
      - pgdumps:/pgdumps
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DATABASE=${COMPOSE_PROJECT_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  rclone:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:rclone-${PROJECT_VERSION}
    build: ./app/rclone
    container_name: ${COMPOSE_PROJECT_NAME}_rclone
    hostname: ${COMPOSE_PROJECT_NAME}_rclone
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - pgdumps:/pgdumps:ro
      - geodatadir:/opt/geoserver/data_dir:ro
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  mapproxy:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:mapproxy-${PROJECT_VERSION}
    build: ./app/mapproxy
    container_name: ${COMPOSE_PROJECT_NAME}_mapproxy
    hostname: ${COMPOSE_PROJECT_NAME}_mapproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_mapproxy.loadBalancer.server.port=8080"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mapproxy.rule=Host(`mapproxy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mapproxy.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mapproxy.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mapproxy.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_mapproxy.middlewares=cache-headers"
    depends_on:
      - geoserver
    volumes:
      - ./app/mapproxy:/mapproxy
    restart: on-failure
