FROM node:16-alpine
RUN apk update && apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@7.18.1 --activate
WORKDIR '/app'
COPY ./package.json ./
COPY ./package-lock.json ./
RUN pnpm install
COPY . .
CMD ["pnpm", "run", "dev"]